### ISSUE TITLE
breaking when you cancel file selection

### ISSUE THREAD

**Issue by mokhosh** [davidstutz/bootstrap-file-upload#1]
first of all thanks for this minimal and nice piece of code. i love minimal and i love nice, so bravo.

my issue is when you hit the button but then decide to cancel selection (and this might happen often after you have already selected a file), the button becomes a tiny empty thing instead of defaulting to what ever was there in the beginning.

**Comment by mokhosh** [comment]
maybe you can add a condition like `if (input.val() != "")`

**Comment by davidstutz** [comment]
Thanks for the note. Will fix it.
